# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-05-05 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_intervention', models.CharField(help_text='Enter the interventions title', max_length=300)),
                ('description', models.TextField(help_text='Enter the instervention description intervention', max_length=300)),
                ('adress_intervention', models.TextField(help_text='Enter the instervention description', max_length=300)),
                ('date_intervention', models.TextField(help_text='Enter the instervention date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
